export const podcasts = [
  {
    id: 1,
    creator: "user1",
    title: "podcast1",
    description: "some description stuff",
    imageUrl: "/images/photo1.jpg",
    listening: 1,
    likes: 1,
    featured: true,
    livestream: true,
    episodes: [],
  },
  {
    id: 2,
    creator: "user1",
    title: "podcast2",
    description: "some description stuff",
    imageUrl: "/images/photo2.jpg",
    listening: 1,
    likes: 1,
    featured: true,
    livestream: true,
    episodes: [],
  },
  {
    id: 3,
    creator: "user1",
    title: "podcast3",
    description: "some description stuff",
    imageUrl: "/images/photo3.jpg",
    listening: 1,
    likes: 1,
    featured: true,
    livestream: false,
    episodes: [],
  },
  {
    id: 4,
    creator: "user1",
    title: "podcast4",
    description: "some description stuff",
    imageUrl: "/images/photo4.jpg",
    listening: 1,
    likes: 1,
    featured: true,
    livestream: false,
    episodes: [],
  },
  {
    id: 5,
    creator: "user1",
    title: "podcast5",
    description: "some description stuff",
    imageUrl: "/images/photo5.jpg",
    listening: 1,
    likes: 1,
    featured: true,
    livestream: false,
    episodes: [],
  },
  {
    id: 6,
    creator: "user1",
    title: "podcast6",
    description: "some description stuff",
    imageUrl: "/images/photo6.jpg",
    listening: 1,
    likes: 1,
    featured: true,
    livestream: false,
    episodes: [],
  },
]

export let users = [
  {
    id: 1,
    username: "user1",
    profilePicture: "/images/user1.png",
    tokens: 10,
    nft: 1,
    followers: [
      {
        id: 2,
        username: "user2",
        profilePicture: "/images/user2.png",
        tokens: 10,
        nft: 1,
        followers: 1,
        followings: 1,
        bio: "Here goes bio",
        favoriteEpisodes: [],
        podcasts: [],
      },
    ], // each obj represents user
    followings: [], // same as above
    bio: "Here goes bio",
    favoriteEpisodes: [],
    podcasts: [
      {
        id: 1,
        creator: "user1",
        title: "podcast1",
        description: "some description stuff",
        imageUrl: "/images/photo1.jpg",
        listening: 1,
        likes: 1,
        featured: true,
        livestream: true,
        episodes: [
          {
            id: 1,
            title: "episode1",
            pinned: false,
            likes: 1,
            listening: 1,
            comments: [],
            poll:'',
            host: "user1",
            participants: [
              {
                id: 1,
                username: "participant1",
                profilePicture: "/images/photo1.jpg",
              },
              {
                id: 2,
                username: "participant2",
                profilePicture: "/images/photo1.jpg",
              },
              {
                id: 3,
                username: "participant3",
                profilePicture: "/images/photo1.jpg",
              },
            ],
            url: "/audio/audio1.mp3",
          },
          {
            id: 2,
            title: "episode2",
            pinned: false,
            likes: 1,
            listening: 1,
            comments: [],
            poll:'',
            host: "user1",
            participants: [
              {
                id: 1,
                username: "participant1",
                profilePicture: "/images/photo1.jpg",
              },
              {
                id: 2,
                username: "participant2",
                profilePicture: "/images/photo1.jpg",
              },
              {
                id: 3,
                username: "participant3",
                profilePicture: "/images/photo1.jpg",
              },
            ],
            url: "/audio/audio2.mp3",
          },
        ],
      },
      {
        id: 2,
        creator: "user1",
        title: "podcast2",
        description: "some description stuff",
        imageUrl: "/images/photo2.jpg",
        listening: 1,
        likes: 1,
        featured: true,
        livestream: true,
        episodes: [
          {
            id: 3,
            title: "episode1",
            pinned: false,
            likes: 1,
            listening: 1,
            comments: [],
            poll:'',
            host: "user1",
            participants: [
              {
                id: 1,
                username: "participant1",
                profilePicture: "/images/photo1.jpg",
              },
              {
                id: 2,
                username: "participant2",
                profilePicture: "/images/photo1.jpg",
              },
              {
                id: 3,
                username: "participant3",
                profilePicture: "/images/photo1.jpg",
              },
            ],
            url: "/audio/audio7.mp3",
          },
        ],
      },
      {
        id: 3,
        creator: "user1",
        title: "podcast3",
        description: "some description stuff",
        imageUrl: "/images/photo3.jpg",
        listening: 1,
        likes: 1,
        featured: true,
        livestream: false,
        episodes: [],
      },
      {
        id: 4,
        creator: "user1",
        title: "podcast4",
        description: "some description stuff",
        imageUrl: "/images/photo4.jpg",
        listening: 1,
        likes: 1,
        featured: true,
        livestream: false,
        episodes: [],
      },
      {
        id: 5,
        creator: "user1",
        title: "podcast5",
        description: "some description stuff",
        imageUrl: "/images/photo5.jpg",
        listening: 1,
        likes: 1,
        featured: true,
        livestream: false,
        episodes: [],
      },
      {
        id: 6,
        creator: "user1",
        title: "podcast6",
        description: "some description stuff",
        imageUrl: "/images/photo6.jpg",
        listening: 1,
        likes: 1,
        featured: true,
        livestream: false,
        episodes: [],
      },
    ],
  },
  {
    id: 2,
    username: "user2",
    profilePicture: "/images/user2.png",
    tokens: 10,
    nft: 1,
    followers: [], // each obj represents user
    followings: [], // same as above
    bio: "Here goes bio",
    favoriteEpisodes: [],
    podcasts: [],
  },
]
